name: Passion∞
favicon: null
layout_spectrum: 0.25995
typography_spectrum: 0.64701
title: 'Do it with passion or not at all. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3e3cf'
    - '#1b001a'
    - '#87959c'
    - '#524e63'
    - '#73754a'
  brandStrength: 0.19943535304628313
  lightness: 0.7788007569033653
  saturation: 0.6986998768988997
  rhythmicContrast: 0.4992572902701795
purpose: []
